---
name: tests

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 0"  # run once a week on Sunday

jobs:
  build:
    strategy:
      matrix:
        config:
          - ["Py3.11-Plone6.1", "6.1", "3.11"]
          - ["Py3.12-Plone6.1", "6.1", "3.12"]
          - ["Py3.13-Plone6.1", "6.1", "3.13"]
    runs-on: ubuntu-latest
    name: ${{ matrix.config[0] }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.config[2] }}
      - name: Install necessary dependencies
        run: |
          sudo apt update
          sudo apt install -y libldap2-dev libsasl2-dev libssl-dev
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            **/eggs
            **/downloads
          key: ${{ runner.os }}-cache-${{ hashFiles('setup.*', '*.cfg') }}-${{ matrix.config[0] }}  # yamllint disable-line rule:line-length
          restore-keys: |
            ${{ runner.os }}-cache-
      - name: Pre commit
        uses: pre-commit/action@v3.0.0
        if: ${{ matrix.config[2] == '3.12' }}
      - name: Install dependencies
        run: |
          sudo locale-gen en_US.UTF-8 nl_NL@euro
          python -m venv .
          bin/pip install -r "requirements-${{ matrix.config[1] }}.txt"
          bin/buildout -c .github-${{ matrix.config[1] }}.cfg
      - name: Test
        run: |
          bin/coverage run bin/test -s osha.oira
          bin/coverage report --fail-under=38 -i
        env:
          zope_i18n_compile_mo_files: 1
